"""constrain_department_enum

Revision ID: 9aff473cd4a6
Revises: 0002_add_rejected
Create Date: 2026-06-25 01:14:43.631164
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9aff473cd4a6'
down_revision: Union[str, None] = '0002_add_rejected'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create enum type first
    department_enum = postgresql.ENUM('IT-Security', 'KYC/AML', 'Retail Banking', 'Treasury', 'Legal', 'Risk', name='department_enum')
    department_enum.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_log', 'event_type',
               existing_type=sa.TEXT(),
               comment='e.g. circular_ingested, map_extracted, judgment_made',
               existing_nullable=False)
    op.alter_column('audit_log', 'entity_type',
               existing_type=sa.TEXT(),
               comment='e.g. circular, map_item, evidence, judgment',
               existing_nullable=False)
    op.alter_column('audit_log', 'payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Full input/output snapshot',
               existing_nullable=False)
    op.alter_column('audit_log', 'input_hash',
               existing_type=sa.TEXT(),
               comment='SHA-256 of input',
               existing_nullable=True)
    op.alter_column('audit_log', 'output_hash',
               existing_type=sa.TEXT(),
               comment='SHA-256 of output',
               existing_nullable=True)
    op.alter_column('audit_log', 'model_version',
               existing_type=sa.TEXT(),
               comment='e.g. claude-sonnet-4-6',
               existing_nullable=True)
    op.alter_column('audit_log', 'actor',
               existing_type=sa.TEXT(),
               comment="User email or 'system'",
               existing_nullable=True)
    op.alter_column('circulars', 'source_hash',
               existing_type=sa.TEXT(),
               comment='SHA-256 of raw content',
               existing_nullable=False)
    op.alter_column('circulars', 'title',
               existing_type=sa.TEXT(),
               comment='Extracted from document',
               existing_nullable=True)
    op.alter_column('evidence_submissions', 'submitted_by',
               existing_type=sa.TEXT(),
               comment='Department officer name/email',
               existing_nullable=False)
    op.alter_column('map_items', 'parent_map_id',
               existing_type=sa.UUID(),
               comment='For child MAPs created by splitting',
               existing_nullable=True)
    op.alter_column('map_items', 'what',
               existing_type=sa.TEXT(),
               comment='What action must be done',
               existing_nullable=False)
    op.alter_column('map_items', 'department',
               existing_type=sa.TEXT(),
               type_=sa.Enum('IT-Security', 'KYC/AML', 'Retail Banking', 'Treasury', 'Legal', 'Risk', name='department_enum', create_constraint=True),
               postgresql_using="department::department_enum",
               comment='Routed department',
               existing_nullable=False)
    op.alter_column('map_items', 'evidence_type',
               existing_type=sa.TEXT(),
               comment='Expected evidence description',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('map_items', 'evidence_type',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Expected evidence description',
               existing_nullable=False)
    op.alter_column('map_items', 'department',
               existing_type=sa.Enum('IT-Security', 'KYC/AML', 'Retail Banking', 'Treasury', 'Legal', 'Risk', name='department_enum', create_constraint=True),
               type_=sa.TEXT(),
               comment=None,
               existing_comment='Routed department',
               existing_nullable=False)
    op.alter_column('map_items', 'what',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='What action must be done',
               existing_nullable=False)
    op.alter_column('map_items', 'parent_map_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='For child MAPs created by splitting',
               existing_nullable=True)
    op.alter_column('evidence_submissions', 'submitted_by',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Department officer name/email',
               existing_nullable=False)
    op.alter_column('circulars', 'title',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Extracted from document',
               existing_nullable=True)
    op.alter_column('circulars', 'source_hash',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='SHA-256 of raw content',
               existing_nullable=False)
    op.alter_column('audit_log', 'actor',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment="User email or 'system'",
               existing_nullable=True)
    op.alter_column('audit_log', 'model_version',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='e.g. claude-sonnet-4-6',
               existing_nullable=True)
    op.alter_column('audit_log', 'output_hash',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='SHA-256 of output',
               existing_nullable=True)
    op.alter_column('audit_log', 'input_hash',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='SHA-256 of input',
               existing_nullable=True)
    op.alter_column('audit_log', 'payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Full input/output snapshot',
               existing_nullable=False)
    op.alter_column('audit_log', 'entity_type',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='e.g. circular, map_item, evidence, judgment',
               existing_nullable=False)
    op.alter_column('audit_log', 'event_type',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='e.g. circular_ingested, map_extracted, judgment_made',
               existing_nullable=False)
    # ### end Alembic commands ###
    
    # Drop enum type
    department_enum = postgresql.ENUM('IT-Security', 'KYC/AML', 'Retail Banking', 'Treasury', 'Legal', 'Risk', name='department_enum')
    department_enum.drop(op.get_bind(), checkfirst=True)
